phrase:
  #project_id: f775bdd3a65aa5ab48d9fb09a21f7635
  project_id: 7007dc78-1623-4cc9-b2be-8de3815b84ad
  push:
    sources:
      - file: ./locales/<locale_code>.json
        params:
          file_format: simple_json
          locale_code: en
          autotranslate: true
  pull:
    targets:
      - file: ./locales/<locale_code>.json
        params:
          file_format: simple_json