phrase:
  project_id: f775bdd3a65aa5ab48d9fb09a21f7635

push:
  sources:
    - file: ./<locale_code>.json
      params:
        file_format: simple_json
        locale_code: en
        update_translations: true

pull:
  targets:
    - file: ./<locale_code>.json
      params:
        file_format: simple_json