phrase:
  #project_id: f775bdd3a65aa5ab48d9fb09a21f7635
  project_id: 6b03427ed28ab969c1f9f67f7a85b7ed
  push:
    sources:
      - file: ./locales/<locale_code>.json
        params:
          file_format: simple_json
          locale_code: en
          autotranslate: true
  pull:
    targets:
      - file: ./locales/<locale_code>.json
        params:
          file_format: simple_json
